import "@/styles/globals.css";

import Root from "./_rootLayout";
import { getServerAuthSession } from "@/server/auth";
import { api } from "@/trpc/server";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  const requiresSetup = await api.setup.getRequiresSetup();
  return (
    <Root children={children} session={session} requiresSetup={requiresSetup} />
  );
}
